'use strict';
const VERSION='1.1.0';
const STORAGE_KEY='mon-budget-data-v2';
const OLD_STORAGE_KEY='mon-budget-data-v1';
const money=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'});
const ICONS=['🏠','🛒','📈','👤','👥','🏦','🚗','💡','📱','🎯','💳','🧾','🍽️','🧸'];
const COLORS=['#1667d9','#2f9e5b','#e58a00','#8e56c7','#dc4451','#665ed1','#128ca8','#a97900'];
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const expense=(label,amount)=>({id:uid(),label,amount});
const incomeSource=(label,amount)=>({id:uid(),label,amount});
const envelope=(name,description,icon,color,planned,expenses=[])=>({id:uid(),name,description,icon,color,planned,expenses});
const seed=()=>({version:VERSION,activeTab:'overview',settings:{privacy:false},spaces:{personal:{name:'Personnel',incomeSources:[incomeSource('Salaire',2709)],envelopes:[
 envelope('Livret A','Charges fixes','🏠','#1667d9',320,[expense('Abonnement YouTube',6.5),expense('Péage et stationnement',8),expense('Assurance automobile',63),expense('Traiteur',115),expense('Carburant',103),expense('Abonnement ChatGPT',23),expense('Abonnement SFR',8)]),
 envelope('Boursobank','Alimentaire et loisirs','🛒','#2f9e5b',200,[expense('Alimentation et restaurant',111.5),expense('Shopping et loisirs',104)]),
 envelope('Revolut','Épargne, crypto et bourse','📈','#e58a00',500,[expense('Épargne Rose',30),expense('Crypto et bourse',470)]),
 envelope('Alizée Cristel','Virement','👤','#8e56c7',150,[expense('Pension Rose',150)]),
 envelope('Compte commun','Virement vers le foyer','👥','#dc4451',1200,[expense('Virement mensuel',1200)]),
 envelope('LEP','Épargne de précaution','🏦','#665ed1',150,[expense('Réserve',150)])]},shared:{name:'Compte commun',incomeSources:[incomeSource('Votre contribution',1200),incomeSource('Contribution du conjoint',1200)],envelopes:[
 envelope('Logement','Loyer et charges','🏠','#1667d9',1150,[expense('Loyer',950),expense('Électricité',110),expense('Internet',40)]),
 envelope('Courses','Alimentation du foyer','🛒','#2f9e5b',500,[expense('Courses principales',310)]),
 envelope('Transport','Mobilité commune','🚗','#e58a00',220,[expense('Carburant',120)]),
 envelope('Maison','Entretien et équipement','💡','#8e56c7',180,[expense('Produits ménagers',42)]),
 envelope('Loisirs','Sorties et activités','🍽️','#dc4451',200,[expense('Restaurant',75)]),
 envelope('Épargne commune','Projets du foyer','🏦','#665ed1',150,[expense('Virement épargne',150)])]}}});
let state=load();state.settings??={privacy:false};if(!['overview','personal','shared','analysis','settings'].includes(state.activeTab))state.activeTab='overview';migrateIncomeSources();let openEnvelopeId=null;let editorContext=null;
const $=s=>document.querySelector(s);
const els={overviewView:$('#overviewView'),combinedAvailable:$('#combinedAvailable'),overviewMessage:$('#overviewMessage'),spaceOverviewCards:$('#spaceOverviewCards'),alertList:$('#alertList'),screenEyebrow:$('#screenEyebrow'),screenTitle:$('#screenTitle'),quickEditBtn:$('#quickEditBtn'),privacyBtn:$('#privacyBtn'),privacyPreview:$('#privacyPreview'),privacySwitch:$('#privacySwitch'),incomeSourceList:$('#incomeSourceList'),budgetView:$('#budgetView'),analysisView:$('#analysisView'),settingsView:$('#settingsView'),available:$('#availableAmount'),income:$('#incomeAmount'),planned:$('#plannedAmount'),spent:$('#spentAmount'),heroMessage:$('#heroMessage'),heroPercent:$('#heroPercent'),heroOrb:$('.hero-orb'),list:$('#envelopeList'),template:$('#envelopeTemplate'),dialog:$('#editorDialog'),form:$('#editorForm'),fields:$('#editorFields'),dialogTitle:$('#dialogTitle'),dialogEyebrow:$('#dialogEyebrow'),deleteArea:$('#deleteArea'),personalNamePreview:$('#personalNamePreview'),sharedNamePreview:$('#sharedNamePreview')};
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved?.spaces?.personal&&saved?.spaces?.shared)return saved;const old=JSON.parse(localStorage.getItem(OLD_STORAGE_KEY));if(old?.months){const latest=old.months[old.selectedMonth]||Object.values(old.months)[0];const fresh=seed();if(latest){fresh.spaces.personal.income=Number(latest.income||0);fresh.spaces.personal.envelopes=latest.envelopes||[];}return fresh;}}catch(e){console.warn(e)}return seed()}
function migrateIncomeSources(){for(const key of ['personal','shared']){const space=state.spaces[key];if(!Array.isArray(space.incomeSources)){space.incomeSources=[incomeSource(key==='personal'?'Revenu principal':'Contributions',Number(space.income||0))]}delete space.income}}
function save(){state.version=VERSION;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));return true}catch(error){console.error('Sauvegarde impossible',error);alert('La sauvegarde locale a échoué. Vérifiez l’espace disponible sur votre appareil.');return false}}
function activeSpace(){return state.spaces[state.activeTab]}
function spent(e){return e.expenses.reduce((s,x)=>s+Number(x.amount||0),0)}
function totals(space=activeSpace()){const planned=space.envelopes.reduce((s,e)=>s+Number(e.planned||0),0);const actual=space.envelopes.reduce((s,e)=>s+spent(e),0);const income=(space.incomeSources||[]).reduce((sum,x)=>sum+Number(x.amount||0),0);return{income,planned,actual,available:income-actual}}
function fmt(n){return state.settings?.privacy?'•••• €':money.format(Number(n||0))}
function render(){
  const overview=state.activeTab==='overview',analysis=state.activeTab==='analysis',settings=state.activeTab==='settings',budget=!overview&&!analysis&&!settings;
  els.overviewView.classList.toggle('active',overview);els.budgetView.classList.toggle('active',budget);els.analysisView.classList.toggle('active',analysis);els.settingsView.classList.toggle('active',settings);
  document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.activeTab));
  els.quickEditBtn.hidden=!budget;els.privacyBtn.hidden=settings;els.privacyBtn.textContent=state.settings?.privacy?'◎':'◉';els.privacyBtn.setAttribute('aria-label',state.settings?.privacy?'Afficher les montants':'Masquer les montants');els.privacyPreview.textContent=state.settings?.privacy?'Activé':'Désactivé';els.privacySwitch.textContent=state.settings?.privacy?'●':'○';els.privacySwitch.classList.toggle('active',Boolean(state.settings?.privacy));
  els.screenEyebrow.textContent=overview?'SYNTHÈSE':analysis?'INDICATEURS':settings?'APPLICATION':state.activeTab==='personal'?'ESPACE PERSONNEL':'ESPACE PARTAGÉ';
  els.screenTitle.textContent=overview?'Mon Budget':analysis?'Analyse':settings?'Réglages':activeSpace().name;
  els.personalNamePreview.textContent=state.spaces.personal.name;els.sharedNamePreview.textContent=state.spaces.shared.name;
  if(overview){renderOverview();return}if(analysis){renderAnalysis();return}if(settings)return;
  const t=totals();els.available.textContent=fmt(t.available);els.income.textContent=fmt(t.income);els.planned.textContent=fmt(t.planned);els.spent.textContent=fmt(t.actual);
  const rate=t.income>0?Math.round(t.actual/t.income*100):0;els.heroPercent.textContent=`${rate}%`;els.heroOrb.style.setProperty('--progress',`${Math.min(rate,100)}%`);els.available.classList.toggle('negative',t.available<0);
  els.heroMessage.textContent=t.available<0?'Les dépenses dépassent les revenus.':rate>=90?'Votre marge disponible devient faible.':'Votre budget permanent est sous contrôle.';
  renderIncomeSources();
  els.list.replaceChildren();if(!activeSpace().envelopes.length){const p=document.createElement('p');p.className='empty-state';p.textContent='Aucune enveloppe. Ajoutez votre première répartition.';els.list.append(p)}else activeSpace().envelopes.forEach(e=>els.list.append(renderEnvelope(e)))
}

function renderIncomeSources(){
  els.incomeSourceList.replaceChildren();
  const sources=activeSpace().incomeSources||[];
  if(!sources.length){const p=document.createElement('p');p.className='empty-state';p.textContent='Aucune source de revenu. Ajoutez une entrée pour calculer le disponible.';els.incomeSourceList.append(p);return}
  sources.forEach(source=>{const row=document.createElement('button');row.type='button';row.className='income-source-row';row.innerHTML='<span class="income-source-icon">＋</span><span class="income-source-copy"><strong></strong><small>Revenu permanent</small></span><strong class="income-source-amount"></strong><span class="income-source-arrow">›</span>';row.querySelector('.income-source-copy strong').textContent=source.label;row.querySelector('.income-source-amount').textContent=fmt(source.amount);row.onclick=()=>openIncomeSourceEditor(source.id);els.incomeSourceList.append(row)})
}

function renderOverview(){
  const entries=['personal','shared'].map(key=>({key,space:state.spaces[key],totals:totals(state.spaces[key])}));
  const combined=entries.reduce((sum,x)=>sum+x.totals.available,0);els.combinedAvailable.textContent=fmt(combined);els.combinedAvailable.classList.toggle('negative',combined<0);
  els.overviewMessage.textContent=combined<0?'La situation globale demande votre attention.':'Somme disponible sur vos deux espaces.';
  els.spaceOverviewCards.replaceChildren();
  entries.forEach(({key,space,totals:t})=>{const rate=t.income?Math.round(t.actual/t.income*100):0;const card=document.createElement('button');card.type='button';card.className='space-overview-card';card.innerHTML='<span class="space-card-icon"></span><span class="space-card-copy"><small></small><strong></strong><em></em></span><span class="space-card-arrow">›</span><span class="mini-track"><i></i></span>';card.querySelector('.space-card-icon').textContent=key==='personal'?'◉':'◎';card.querySelector('small').textContent=key==='personal'?'PERSONNEL':'COMPTE COMMUN';card.querySelector('strong').textContent=fmt(t.available);card.querySelector('em').textContent=`${fmt(t.actual)} dépensés sur ${fmt(t.income)}`;card.querySelector('i').style.width=`${Math.min(rate,100)}%`;card.querySelector('i').className=rate>100?'over':rate>=85?'warn':'';card.onclick=()=>{state.activeTab=key;save();render()};els.spaceOverviewCards.append(card)});
  const alerts=[];entries.forEach(({key,space})=>space.envelopes.forEach(e=>{const p=Number(e.planned||0),a=spent(e),ratio=p?a/p:(a?2:0);if(ratio>=1)alerts.push({level:'danger',space:key,name:e.name,text:`Budget dépassé de ${fmt(a-p)}`});else if(ratio>=.85)alerts.push({level:'warning',space:key,name:e.name,text:`${Math.round(ratio*100)} % du budget utilisé`})}));
  els.alertList.replaceChildren();if(!alerts.length){const ok=document.createElement('div');ok.className='alert-card success';ok.innerHTML='<span>✓</span><div><strong>Tout est sous contrôle</strong><small>Aucune enveloppe proche de sa limite.</small></div>';els.alertList.append(ok)}else alerts.slice(0,6).forEach(a=>{const row=document.createElement('button');row.type='button';row.className=`alert-card ${a.level}`;row.innerHTML='<span>!</span><div><strong></strong><small></small></div><b>›</b>';row.querySelector('strong').textContent=a.name;row.querySelector('small').textContent=a.text;row.onclick=()=>{state.activeTab=a.space;openEnvelopeId=state.spaces[a.space].envelopes.find(e=>e.name===a.name)?.id||null;save();render()};els.alertList.append(row)})
}

function renderAnalysis(){
  const entries=['personal','shared'].map(key=>({key,space:state.spaces[key],totals:totals(state.spaces[key])}));
  const income=entries.reduce((sum,x)=>sum+x.totals.income,0),actual=entries.reduce((sum,x)=>sum+x.totals.actual,0),available=income-actual,rate=income?Math.round(actual/income*100):0;
  $('#analysisSpent').textContent=fmt(actual);$('#globalMargin').textContent=fmt(available);$('#globalMargin').classList.toggle('negative',available<0);$('#commitmentRate').textContent=`${rate} %`;
  const bar=$('#analysisBar');bar.style.width=`${Math.min(rate,100)}%`;bar.className=rate>100?'over':rate>=85?'warn':'';
  $('#analysisCaption').textContent=rate>100?'Les dépenses enregistrées dépassent les revenus cumulés.':rate>=85?'La marge globale est réduite.':'La répartition globale conserve une marge confortable.';
  const all=[];entries.forEach(({key,space})=>space.envelopes.forEach(e=>all.push({key,space:space.name,e,amount:spent(e)})));all.sort((a,b)=>b.amount-a.amount);const max=Math.max(...all.map(x=>x.amount),1);
  const ranking=$('#topEnvelopeList');ranking.replaceChildren();all.slice(0,5).forEach((item,index)=>{const row=document.createElement('button');row.type='button';row.className='ranking-row';row.innerHTML='<div class="ranking-head"><div class="ranking-name"><span></span><div><strong></strong><small></small></div></div><div class="ranking-value"><strong></strong><small></small></div></div><div class="ranking-track"><i></i></div>';row.querySelector('.ranking-name>span').textContent=item.e.icon||'💳';row.querySelector('.ranking-name strong').textContent=item.e.name;row.querySelector('.ranking-name small').textContent=item.space;row.querySelector('.ranking-value strong').textContent=fmt(item.amount);row.querySelector('.ranking-value small').textContent=`N° ${index+1}`;row.querySelector('i').style.width=`${item.amount/max*100}%`;row.onclick=()=>{state.activeTab=item.key;openEnvelopeId=item.e.id;save();render()};ranking.append(row)});
  if(!all.length){const p=document.createElement('p');p.className='empty-state';p.textContent='Aucune enveloppe à analyser.';ranking.append(p)}
  const comparison=$('#spaceComparison');comparison.replaceChildren();entries.forEach(({key,space,totals:t})=>{const r=t.income?Math.round(t.actual/t.income*100):0;const row=document.createElement('button');row.type='button';row.className='comparison-row';row.innerHTML='<div class="comparison-head"><div><strong></strong><small></small></div><strong class="comparison-rate"></strong></div><div class="comparison-track"><i></i></div><div class="comparison-stats"><div><span>Revenus</span><strong></strong></div><div><span>Dépensé</span><strong></strong></div><div><span>Disponible</span><strong></strong></div></div>';row.querySelector('.comparison-head strong').textContent=space.name;row.querySelector('.comparison-head small').textContent=key==='personal'?'Budget personnel':'Budget partagé';row.querySelector('.comparison-rate').textContent=`${r} %`;row.querySelector('.comparison-track i').style.width=`${Math.min(r,100)}%`;const vals=row.querySelectorAll('.comparison-stats strong');vals[0].textContent=fmt(t.income);vals[1].textContent=fmt(t.actual);vals[2].textContent=fmt(t.available);vals[2].classList.toggle('negative',t.available<0);row.onclick=()=>{state.activeTab=key;save();render()};comparison.append(row)});
}

function renderEnvelope(e){const node=els.template.content.firstElementChild.cloneNode(true);const actual=spent(e),planned=Number(e.planned||0),diff=planned-actual,ratio=planned?actual/planned:(actual?1:0),open=e.id===openEnvelopeId;node.dataset.id=e.id;node.style.setProperty('--card-accent',e.color||COLORS[0]);node.classList.toggle('open',open);const summary=node.querySelector('.envelope-summary');summary.setAttribute('aria-expanded',String(open));node.querySelector('.envelope-icon').textContent=e.icon||'💳';node.querySelector('.envelope-name').textContent=e.name;node.querySelector('.envelope-description').textContent=e.description||'Sans description';node.querySelector('.envelope-amount').textContent=fmt(actual);node.querySelector('.envelope-progress-label').textContent=`${Math.round(ratio*100)} % du budget`;node.querySelector('.planned-value').textContent=fmt(planned);node.querySelector('.spent-value').textContent=fmt(actual);const d=node.querySelector('.difference-value');d.textContent=`${diff<0?'−':''}${fmt(Math.abs(diff))}`;d.classList.add(diff<0?'negative':'positive');const fill=node.querySelector('.progress-fill');fill.style.width=`${Math.min(Math.max(ratio*100,0),100)}%`;fill.style.background=ratio>1?'var(--negative)':ratio>=.85?'var(--warning)':'var(--positive)';node.querySelector('.expense-count').textContent=`DÉPENSES (${e.expenses.length})`;const list=node.querySelector('.expense-list');if(!e.expenses.length){const p=document.createElement('p');p.className='empty-state';p.textContent='Aucune dépense enregistrée.';list.append(p)}else e.expenses.forEach(x=>{const row=document.createElement('div');row.className='expense-row';row.innerHTML='<strong></strong><span></span><button type="button" aria-label="Modifier">•••</button>';row.querySelector('strong').textContent=x.label;row.querySelector('span').textContent=fmt(x.amount);row.querySelector('button').onclick=()=>openExpenseEditor(e.id,x.id);list.append(row)});summary.onclick=()=>{openEnvelopeId=open?null:e.id;navigator.vibrate?.(8);render()};node.querySelector('.edit-envelope').onclick=()=>openEnvelopeEditor(e.id);node.querySelector('.add-expense').onclick=()=>openExpenseEditor(e.id);const tools=node.querySelector('.expense-header>div');tools.insertAdjacentHTML('afterbegin','<button class="text-button duplicate-envelope" type="button">Dupliquer</button>');tools.querySelector('.duplicate-envelope').onclick=()=>duplicateEnvelope(e.id);const index=activeSpace().envelopes.findIndex(x=>x.id===e.id);const up=node.querySelector('.move-up'),down=node.querySelector('.move-down');up.disabled=index===0;down.disabled=index===activeSpace().envelopes.length-1;up.onclick=()=>moveEnvelope(e.id,-1);down.onclick=()=>moveEnvelope(e.id,1);return node}

function moveEnvelope(id,direction){const items=activeSpace().envelopes,index=items.findIndex(e=>e.id===id),next=index+direction;if(index<0||next<0||next>=items.length)return;[items[index],items[next]]=[items[next],items[index]];openEnvelopeId=id;navigator.vibrate?.(10);save();render()}
function duplicateEnvelope(id){const source=activeSpace().envelopes.find(e=>e.id===id);if(!source)return;const copy=structuredClone(source);copy.id=uid();copy.name=`${source.name} – copie`;copy.expenses=copy.expenses.map(x=>({...x,id:uid()}));activeSpace().envelopes.push(copy);openEnvelopeId=copy.id;save();render()}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function input(name,label,value='',type='text',attrs=''){return `<div class="form-field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${attrs}></div>`}
function select(name,label,values,selected){return `<div class="form-field"><label for="${name}">${label}</label><select id="${name}" name="${name}">${values.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${v}</option>`).join('')}</select></div>`}
function showEditor({title,eyebrow,fields,context,deleteLabel}){editorContext=context;els.dialogTitle.textContent=title;els.dialogEyebrow.textContent=eyebrow;els.fields.innerHTML=fields;els.deleteArea.innerHTML=deleteLabel?`<button class="delete-button" id="deleteButton" type="button">${deleteLabel}</button>`:'';if(deleteLabel)$('#deleteButton').onclick=deleteCurrent;els.dialog.showModal();setTimeout(()=>els.fields.querySelector('input')?.focus(),100)}
function openIncomeSourceEditor(id=null){const source=id?activeSpace().incomeSources.find(x=>x.id===id):null;showEditor({title:source?'Modifier le revenu':'Nouvelle source de revenu',eyebrow:activeSpace().name.toUpperCase(),context:{type:'incomeSource',id},deleteLabel:source?'Supprimer cette source':null,fields:input('label','Libellé',source?.label||'','','maxlength="50" required')+input('amount','Montant',source?.amount??'','number','min="0" step="0.01" inputmode="decimal" required')})}
function openEnvelopeEditor(id=null){const e=id?activeSpace().envelopes.find(x=>x.id===id):null;showEditor({title:e?'Modifier l’enveloppe':'Nouvelle enveloppe',eyebrow:'RÉPARTITION',context:{type:'envelope',id},deleteLabel:e?'Supprimer cette enveloppe':null,fields:[input('name','Nom',e?.name||'','','maxlength="40" required'),input('description','Description',e?.description||'','','maxlength="70"'),input('planned','Budget prévu',e?.planned??'','number','min="0" step="0.01" inputmode="decimal" required'),select('icon','Icône',ICONS,e?.icon||ICONS[0]),select('color','Couleur',COLORS,e?.color||COLORS[0])].join('')})}
function openExpenseEditor(envelopeId,id=null){const env=activeSpace().envelopes.find(e=>e.id===envelopeId),x=id?env.expenses.find(y=>y.id===id):null;showEditor({title:x?'Modifier la dépense':'Nouvelle dépense',eyebrow:env.name.toUpperCase(),context:{type:'expense',envelopeId,id},deleteLabel:x?'Supprimer cette dépense':null,fields:input('label','Libellé',x?.label||'','','maxlength="60" required')+input('amount','Montant',x?.amount??'','number','min="0" step="0.01" inputmode="decimal" required')})}
function openRename(spaceKey){showEditor({title:'Renommer l’espace',eyebrow:'RÉGLAGES',context:{type:'rename',spaceKey},fields:input('name','Nom affiché',state.spaces[spaceKey].name,'','maxlength="30" required')})}
function deleteCurrent(){if(editorContext.type==='envelope'&&confirm('Supprimer cette enveloppe et toutes ses dépenses ?'))activeSpace().envelopes=activeSpace().envelopes.filter(e=>e.id!==editorContext.id);else if(editorContext.type==='incomeSource'&&confirm('Supprimer cette source de revenu ?'))activeSpace().incomeSources=activeSpace().incomeSources.filter(x=>x.id!==editorContext.id);else if(editorContext.type==='expense'&&confirm('Supprimer cette dépense ?')){const env=activeSpace().envelopes.find(e=>e.id===editorContext.envelopeId);env.expenses=env.expenses.filter(x=>x.id!==editorContext.id)}else return;save();els.dialog.close();openEnvelopeId=null;render()}
els.form.onsubmit=e=>{e.preventDefault();const f=new FormData(els.form);if(editorContext.type==='incomeSource'){const payload={label:String(f.get('label')).trim(),amount:Number(f.get('amount'))};if(editorContext.id)Object.assign(activeSpace().incomeSources.find(x=>x.id===editorContext.id),payload);else activeSpace().incomeSources.push({id:uid(),...payload})}if(editorContext.type==='rename')state.spaces[editorContext.spaceKey].name=String(f.get('name')).trim();if(editorContext.type==='envelope'){const payload={name:String(f.get('name')).trim(),description:String(f.get('description')).trim(),planned:Number(f.get('planned')),icon:String(f.get('icon')),color:String(f.get('color'))};if(editorContext.id)Object.assign(activeSpace().envelopes.find(x=>x.id===editorContext.id),payload);else{const id=uid();activeSpace().envelopes.push({id,...payload,expenses:[]});openEnvelopeId=id}}if(editorContext.type==='expense'){const env=activeSpace().envelopes.find(x=>x.id===editorContext.envelopeId);const payload={label:String(f.get('label')).trim(),amount:Number(f.get('amount'))};if(editorContext.id)Object.assign(env.expenses.find(x=>x.id===editorContext.id),payload);else env.expenses.push({id:uid(),...payload});openEnvelopeId=env.id}save();els.dialog.close();render()};
$('#cancelDialogBtn').onclick=$('#closeDialogBtn').onclick=()=>els.dialog.close();$('#addEnvelopeBtn').onclick=()=>openEnvelopeEditor();$('#addIncomeBtn').onclick=()=>openIncomeSourceEditor();els.quickEditBtn.onclick=()=>openIncomeSourceEditor();els.privacyBtn.onclick=()=>{state.settings.privacy=!state.settings.privacy;navigator.vibrate?.(8);save();render()};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.tab;openEnvelopeId=null;save();render()});
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='rename-personal')openRename('personal');if(a==='rename-shared')openRename('shared');if(a==='privacy'){state.settings.privacy=!state.settings.privacy;save();render()}if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='mon-budget-sauvegarde.json';link.click();URL.revokeObjectURL(url)}if(a==='reset'&&confirm('Réinitialiser toutes les données de l’application ?')){state=seed();save();render()}});
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!imported?.spaces?.personal||!imported?.spaces?.shared)throw new Error();if(confirm('Importer cette sauvegarde et remplacer les données actuelles ?')){state=imported;state.activeTab='settings';state.settings??={privacy:false};migrateIncomeSources();save();render()}}catch{alert('Ce fichier de sauvegarde est invalide.')}e.target.value=''};
let deferredInstallPrompt=null;
const installButton=document.querySelector('[data-action="install"]');
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;if(installButton){installButton.hidden=false;installButton.disabled=false}});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;if(installButton){installButton.hidden=true;installButton.disabled=true}});
if(installButton){installButton.onclick=async()=>{if(!deferredInstallPrompt){alert('Sur iPhone : touchez Partager, puis « Sur l’écran d’accueil ». Sur ordinateur ou Android, utilisez le menu du navigateur pour installer l’application.');return}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installButton.hidden=true}};
render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(error=>console.warn('Service worker non enregistré',error)));
