'use strict';
const VERSION='1.4.0',money=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}),uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const incomeSource=(label,amount)=>({id:uid(),label,amount}),expense=(label,amount)=>({id:uid(),label,amount}),post=(name,description,icon,expenses=[],type='expense')=>({id:uid(),name,description,icon,color:'#0a84ff',planned:0,expenses,type});
const seed=()=>({version:VERSION,activeTab:'overview',settings:{privacy:false},meta:{createdAt:new Date().toISOString(),revision:0,lastSavedAt:null},spaces:{personal:{name:'Personnel',incomeSources:[incomeSource('Salaire',2709)],envelopes:[post('Charges fixes','Dépenses récurrentes','🏠',[expense('Internet',40),expense('Assurance',63)]),post('Compte commun','Transfert vers le foyer','👥',[expense('Virement',1200)],'transfer'),post('Épargne et investissements','Épargne, crypto et bourse','📈',[expense('Versements',500)],'savings')]},shared:{name:'Compte commun',incomeSources:[incomeSource('Contribution 1',1200),incomeSource('Contribution 2',1200)],envelopes:[post('Logement','Loyer et charges','🏠',[expense('Loyer',950),expense('Électricité',110)]),post('Courses','Alimentation du foyer','🛒',[expense('Courses',330)])]}}});
let state,openId=null,editor=null,pendingImport=null,saveTimer;
const $=s=>document.querySelector(s),els={overview:$('#overviewView'),space:$('#spaceView'),settings:$('#settingsView'),overviewCards:$('#overviewCards'),title:$('#screenTitle'),eyebrow:$('#screenEyebrow'),privacy:$('#privacyBtn'),available:$('#availableAmount'),income:$('#incomeAmount'),outgoing:$('#outgoingAmount'),incomeList:$('#incomeSourceList'),posts:$('#envelopeList'),template:$('#postTemplate'),dialog:$('#editorDialog'),form:$('#editorForm'),fields:$('#editorFields'),dialogTitle:$('#dialogTitle'),dialogEyebrow:$('#dialogEyebrow'),deleteArea:$('#deleteArea'),importDialog:$('#importDialog'),importSummary:$('#importSummary')};
const fmt=n=>state.settings?.privacy?'•••• €':money.format(Number(n||0)),sum=a=>a.reduce((s,n)=>s+Number(n||0),0),spent=e=>sum((e.expenses||[]).map(x=>x.amount)),totals=s=>({income:sum((s.incomeSources||[]).map(x=>x.amount)),outgoing:sum((s.envelopes||[]).map(spent)),available:sum((s.incomeSources||[]).map(x=>x.amount))-sum((s.envelopes||[]).map(spent))});
async function load(){const loaded=await BudgetStorage.load();state=normalize(loaded.state)||seed();if(!['overview','personal','shared','settings'].includes(state.activeTab))state.activeTab='overview';if(loaded.source!=='indexeddb')save(false);render()}
function normalize(raw){if(!raw)return null;let d=raw.state||raw.data||raw;if(d.months){const latest=d.months[d.selectedMonth]||Object.values(d.months)[0],n=seed();if(latest){n.spaces.personal.incomeSources=[incomeSource('Salaire',Number(latest.income||0))];n.spaces.personal.envelopes=latest.envelopes||[]}d=n}if(!d.spaces?.personal||!d.spaces?.shared)return null;d.settings??={privacy:false};d.meta??={createdAt:new Date().toISOString(),revision:0,lastSavedAt:null};for(const [key,s] of Object.entries(d.spaces)){if(!Array.isArray(s.incomeSources))s.incomeSources=[incomeSource(key==='personal'?'Revenu principal':'Contributions',Number(s.income||0))];s.envelopes=Array.isArray(s.envelopes)?s.envelopes:[];for(const e of s.envelopes){e.id??=uid();e.name??='Poste';e.description??='';e.icon??='•';e.expenses=Array.isArray(e.expenses)?e.expenses:[];e.type=['expense','savings','transfer'].includes(e.type)?e.type:(key==='personal'&&/compte commun/i.test(e.name)?'transfer':/épargne|livret|crypto|bourse/i.test(`${e.name} ${e.description}`)?'savings':'expense');for(const x of e.expenses){x.id??=uid();x.label??='Ligne';x.amount=Number(x.amount||0)}}delete s.income}d.version=VERSION;return d}
function save(snapshot=true){state.version=VERSION;state.meta.lastSavedAt=new Date().toISOString();state.meta.revision=(state.meta.revision||0)+1;clearTimeout(saveTimer);saveTimer=setTimeout(()=>BudgetStorage.save(structuredClone(state),{snapshot}).then(renderSaved).catch(()=>alert('Sauvegarde impossible. Exportez vos données.')),150)}
function renderSaved(){const t=state.meta.lastSavedAt?new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'short'}).format(new Date(state.meta.lastSavedAt)):'—';$('#lastSavedPreview').textContent=t;$('#lastSavedHome').textContent=`Dernière sauvegarde : ${t}`}
function activeSpace(){return state.spaces[state.activeTab]}
function render(){const ov=state.activeTab==='overview',set=state.activeTab==='settings';els.overview.classList.toggle('active',ov);els.space.classList.toggle('active',!ov&&!set);els.settings.classList.toggle('active',set);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.activeTab));els.title.textContent=ov?'Accueil':set?'Réglages':activeSpace().name;els.eyebrow.textContent=ov?'VUE D’ENSEMBLE':set?'APPLICATION':state.activeTab==='personal'?'ESPACE PERSONNEL':'ESPACE PARTAGÉ';els.privacy.textContent=state.settings.privacy?'◎':'◉';$('#privacyPreview').textContent=state.settings.privacy?'Activé':'Désactivé';$('#personalNamePreview').textContent=state.spaces.personal.name;$('#sharedNamePreview').textContent=state.spaces.shared.name;renderSaved();if(ov)renderOverview();else if(!set)renderSpace()}
function renderOverview(){els.overviewCards.replaceChildren();for(const key of ['personal','shared']){const s=state.spaces[key],t=totals(s),card=document.createElement('article');card.className=`snapshot-card ${key}`;card.innerHTML=`<div class="snapshot-top"><div><small>${key==='personal'?'Situation personnelle':'Compte commun'}</small><strong>${fmt(t.available)}</strong><span>Disponible</span></div><span>›</span></div><div class="snapshot-metrics"><div><small>Rentrées</small><b>${fmt(t.income)}</b></div><div><small>Sorties</small><b>${fmt(t.outgoing)}</b></div></div><button class="snapshot-link">Voir ${s.name.toLowerCase()}</button>`;card.querySelector('button').onclick=()=>{state.activeTab=key;save(false);render()};els.overviewCards.append(card)}}
function renderSpace(){const t=totals(activeSpace());els.available.textContent=fmt(t.available);els.income.textContent=fmt(t.income);els.outgoing.textContent=fmt(t.outgoing);els.available.style.color=t.available<0?'var(--red)':'';els.incomeList.replaceChildren();for(const src of activeSpace().incomeSources){const r=document.createElement('div');r.className='income-row';r.innerHTML='<div><strong></strong><small>Rentrée d’argent</small></div><b></b><button>•••</button>';r.querySelector('strong').textContent=src.label;r.querySelector('b').textContent=fmt(src.amount);r.querySelector('button').onclick=()=>openIncome(src.id);els.incomeList.append(r)}els.posts.replaceChildren();for(const e of activeSpace().envelopes)els.posts.append(renderPost(e))}
function typeLabel(t){return t==='transfer'?'Transfert':t==='savings'?'Épargne':'Dépense'}
function renderPost(e){const n=els.template.content.firstElementChild.cloneNode(true);n.dataset.id=e.id;n.classList.toggle('open',e.id===openId);n.querySelector('.post-icon').textContent=e.icon;n.querySelector('.post-copy strong').textContent=e.name;n.querySelector('.post-copy small').textContent=`${typeLabel(e.type)} · ${e.description||'Sans description'}`;n.querySelector('.post-amount').textContent=fmt(spent(e));n.querySelector('.post-summary').onclick=()=>{openId=openId===e.id?null:e.id;render()};n.querySelector('.edit-post').onclick=()=>openPost(e.id);n.querySelector('.add-expense').onclick=()=>openExpense(e.id);const list=n.querySelector('.expense-list');if(!e.expenses.length){list.innerHTML='<p class="empty">Aucune ligne enregistrée.</p>'}else for(const x of e.expenses){const r=document.createElement('div');r.className='expense-row';r.innerHTML='<strong></strong><span></span><button>•••</button>';r.querySelector('strong').textContent=x.label;r.querySelector('span').textContent=fmt(x.amount);r.querySelector('button').onclick=()=>openExpense(e.id,x.id);list.append(r)}return n}
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),input=(name,label,value='',type='text')=>`<div class="form-field"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01" inputmode="decimal"':''} required></div>`,select=(name,label,opts,val)=>`<div class="form-field"><label>${label}</label><select name="${name}">${opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select></div>`;
function showEditor(title,eyebrow,fields,ctx,del){editor=ctx;els.dialogTitle.textContent=title;els.dialogEyebrow.textContent=eyebrow;els.fields.innerHTML=fields;els.deleteArea.innerHTML=del?`<button class="delete-button" id="deleteButton" type="button">${del}</button>`:'';if(del)$('#deleteButton').onclick=removeCurrent;els.dialog.showModal()}
function openIncome(id){const x=id?activeSpace().incomeSources.find(v=>v.id===id):null;showEditor(x?'Modifier la rentrée':'Nouvelle rentrée',activeSpace().name.toUpperCase(),input('label','Libellé',x?.label)+input('amount','Montant',x?.amount,'number'),{type:'income',id},x?'Supprimer cette rentrée':null)}
function openPost(id){const e=id?activeSpace().envelopes.find(v=>v.id===id):null;showEditor(e?'Modifier le poste':'Nouveau poste','POSTE FINANCIER',input('name','Nom',e?.name)+input('description','Description',e?.description)+select('type','Nature',['Dépense','Épargne','Transfert'],typeLabel(e?.type||'expense'))+input('icon','Icône',e?.icon||'•'),{type:'post',id},e?'Supprimer ce poste':null)}
function openExpense(postId,id){const e=activeSpace().envelopes.find(v=>v.id===postId),x=id?e.expenses.find(v=>v.id===id):null;showEditor(x?'Modifier la ligne':'Nouvelle ligne',e.name.toUpperCase(),input('label','Libellé',x?.label)+input('amount','Montant',x?.amount,'number'),{type:'expense',postId,id},x?'Supprimer cette ligne':null)}
function openRename(key){showEditor('Renommer l’espace','RÉGLAGES',input('name','Nom',state.spaces[key].name),{type:'rename',key},null)}
els.form.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(els.form));if(editor.type==='income'){let x=editor.id?activeSpace().incomeSources.find(v=>v.id===editor.id):null;if(x){x.label=d.label;x.amount=Number(d.amount)}else activeSpace().incomeSources.push(incomeSource(d.label,Number(d.amount)))}if(editor.type==='post'){let p=editor.id?activeSpace().envelopes.find(v=>v.id===editor.id):null;const type=d.type==='Épargne'?'savings':d.type==='Transfert'?'transfer':'expense';if(p)Object.assign(p,{name:d.name,description:d.description,icon:d.icon,type});else activeSpace().envelopes.push(post(d.name,d.description,d.icon,[],type))}if(editor.type==='expense'){const p=activeSpace().envelopes.find(v=>v.id===editor.postId),x=editor.id?p.expenses.find(v=>v.id===editor.id):null;if(x){x.label=d.label;x.amount=Number(d.amount)}else p.expenses.push(expense(d.label,Number(d.amount)))}if(editor.type==='rename')state.spaces[editor.key].name=d.name;save();els.dialog.close();render()};
function removeCurrent(){if(!confirm('Confirmer la suppression ?'))return;if(editor.type==='income')activeSpace().incomeSources=activeSpace().incomeSources.filter(x=>x.id!==editor.id);if(editor.type==='post')activeSpace().envelopes=activeSpace().envelopes.filter(x=>x.id!==editor.id);if(editor.type==='expense'){const p=activeSpace().envelopes.find(x=>x.id===editor.postId);p.expenses=p.expenses.filter(x=>x.id!==editor.id)}save();els.dialog.close();render()}
function exportBackup(){const blob=new Blob([JSON.stringify({app:'mon-organisation-financiere',version:VERSION,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`organisation-financiere-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function previewImport(file){try{const raw=JSON.parse(await file.text()),d=normalize(raw);if(!d)throw new Error();pendingImport=d;const p=d.spaces.personal,s=d.spaces.shared,lines=[...p.envelopes,...s.envelopes].reduce((n,e)=>n+e.expenses.length,0);els.importSummary.innerHTML=`<div><span>Rentrées</span><b>${p.incomeSources.length+s.incomeSources.length}</b></div><div><span>Postes personnels</span><b>${p.envelopes.length}</b></div><div><span>Postes communs</span><b>${s.envelopes.length}</b></div><div><span>Lignes détaillées</span><b>${lines}</b></div>`;els.importDialog.showModal()}catch{alert('Cette sauvegarde JSON est invalide ou incompatible.')}}
async function confirmImport(){if(!pendingImport)return;await BudgetStorage.save(structuredClone(state),{snapshot:true});state=pendingImport;pendingImport=null;await BudgetStorage.save(structuredClone(state),{snapshot:true});els.importDialog.close();render();alert('Sauvegarde importée avec succès. Toutes vos données ont été restaurées.')}
async function restore(){const snaps=await BudgetStorage.listSnapshots();if(!snaps.length)return alert('Aucune copie locale disponible.');if(confirm('Restaurer la copie locale la plus récente ?')){state=normalize(snaps[0].state)||state;await BudgetStorage.save(structuredClone(state),{snapshot:false});render()}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.tab;openId=null;save(false);render()});els.privacy.onclick=()=>{state.settings.privacy=!state.settings.privacy;save(false);render()};$('#addIncomeBtn').onclick=()=>openIncome();$('#addEnvelopeBtn').onclick=()=>openPost();$('#closeDialogBtn').onclick=$('#cancelDialogBtn').onclick=()=>els.dialog.close();$('#importInput').onchange=e=>{const f=e.target.files[0];if(f)previewImport(f);e.target.value=''};$('#closeImportBtn').onclick=$('#cancelImportBtn').onclick=()=>els.importDialog.close();$('#confirmImportBtn').onclick=confirmImport;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='export')exportBackup();if(a==='restore')restore();if(a==='privacy'){state.settings.privacy=!state.settings.privacy;save(false);render()}if(a==='rename-personal')openRename('personal');if(a==='rename-shared')openRename('shared');if(a==='reset'&&confirm('Effacer toutes les données locales ?')&&confirm('Cette action est irréversible sans sauvegarde JSON.')){state=seed();save();render()}});load();
