'use strict';
const VERSION='2.1.0';
const money=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'});
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const incomeSource=(label,amount)=>({id:uid(),label,amount:Number(amount)||0});
const expense=(label,amount)=>({id:uid(),label,amount:Number(amount)||0});
const post=(name,description,icon,expenses=[],type='expense')=>({id:uid(),name,description,icon,color:'#4d8dff',planned:0,expenses,type});
const forecastItem=(kind,label,amount)=>({id:uid(),kind,label,amount,date:'',status:'planned',source:'current'});
const defaultForecastItems=()=>[
forecastItem('payment','Franchise voiture',375),forecastItem('payment','Télévision',222),forecastItem('payment','Impôts communs',350),forecastItem('payment','Impôts personnels',150),forecastItem('payment','Compte commun',146),forecastItem('payment','Airbnb',863),forecastItem('payment','Compte courant',500),forecastItem('payment','Entretien SEAT',600),forecastItem('payment','Entretien + Contrôle technique Laguna',300),forecastItem('payment','Anniversaire Rose',80),forecastItem('receipt','Dividendes',596),forecastItem('receipt','Psychiatre',85),forecastItem('receipt','Courses',100),forecastItem('receipt','Courses',62)];
const seed=()=>({version:VERSION,activeTab:'overview',settings:{privacy:false},meta:{createdAt:new Date().toISOString(),revision:0,lastSavedAt:null},forecast:{buffer:{target:5000,current:5000},items:defaultForecastItems(),prefillVersion:VERSION},investments:{accounts:[
{id:uid(),name:'Trade Republic',platform:'trade-republic',valueEUR:0,positions:[],updatedAt:null},{id:uid(),name:'SwissBorg',platform:'swissborg',valueEUR:0,positions:[],updatedAt:null},{id:uid(),name:'MERIA',platform:'meria',valueEUR:0,positions:[],updatedAt:null},{id:uid(),name:'Crypto.com',platform:'crypto-com',valueEUR:0,positions:[],updatedAt:null},{id:uid(),name:'Bourse Direct',platform:'bourse-direct',valueEUR:0,positions:[],updatedAt:null}],imports:[]},spaces:{personal:{name:'Personnel',incomeSources:[incomeSource('Salaire',2709)],envelopes:[post('Charges fixes','Dépenses récurrentes','⌂',[expense('Internet',40),expense('Assurance',63)]),post('Compte commun','Transfert vers le foyer','◎',[expense('Virement',1200)],'transfer'),post('Épargne et investissements','Épargne, crypto et bourse','↗',[expense('Versements',500)],'savings')]},shared:{name:'Compte commun',incomeSources:[incomeSource('Contribution 1',1200),incomeSource('Contribution 2',1200)],envelopes:[post('Logement','Loyer et charges','⌂',[expense('Loyer',950),expense('Électricité',110)]),post('Courses','Alimentation du foyer','◫',[expense('Courses',330)])]}}});
let state,openId=null,editor=null,pendingImport=null,pendingStatements=[],saveTimer,saveQueue=Promise.resolve();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const els={overview:$('#overviewView'),space:$('#spaceView'),future:$('#futureView'),investments:$('#investmentsView'),settings:$('#settingsView'),overviewCards:$('#overviewCards'),title:$('#screenTitle'),eyebrow:$('#screenEyebrow'),privacy:$('#privacyBtn'),available:$('#availableAmount'),income:$('#incomeAmount'),outgoing:$('#outgoingAmount'),incomeList:$('#incomeSourceList'),posts:$('#envelopeList'),template:$('#postTemplate'),dialog:$('#editorDialog'),form:$('#editorForm'),fields:$('#editorFields'),dialogTitle:$('#dialogTitle'),dialogEyebrow:$('#dialogEyebrow'),deleteArea:$('#deleteArea'),importDialog:$('#importDialog'),importSummary:$('#importSummary')};
const fmt=n=>state.settings?.privacy?'•••• €':money.format(Number(n||0));
const sum=a=>a.reduce((s,n)=>s+Number(n||0),0),spent=e=>sum((e.expenses||[]).map(x=>x.amount));
const totals=s=>({income:sum((s.incomeSources||[]).map(x=>x.amount)),outgoing:sum((s.envelopes||[]).map(spent)),available:sum((s.incomeSources||[]).map(x=>x.amount))-sum((s.envelopes||[]).map(spent))});
function normalize(raw){if(!raw)return null;let d=raw.state||raw.data||raw;if(d.months){const latest=d.months[d.selectedMonth]||Object.values(d.months)[0],n=seed();if(latest){n.spaces.personal.incomeSources=[incomeSource('Salaire',Number(latest.income||0))];n.spaces.personal.envelopes=latest.envelopes||[]}d=n}if(!d.spaces?.personal||!d.spaces?.shared)return null;d.settings??={privacy:false};d.meta??={createdAt:new Date().toISOString(),revision:0,lastSavedAt:null};d.forecast??={buffer:{target:5000,current:5000},items:[]};d.forecast.buffer??={target:5000,current:5000};d.forecast.items=Array.isArray(d.forecast.items)?d.forecast.items:[];d.investments??={accounts:[],imports:[]};d.investments.accounts=Array.isArray(d.investments.accounts)?d.investments.accounts:[];d.investments.imports=Array.isArray(d.investments.imports)?d.investments.imports:[];const defaults=[['Trade Republic','trade-republic'],['SwissBorg','swissborg'],['MERIA','meria'],['Crypto.com','crypto-com'],['Bourse Direct','bourse-direct']];for(const [name,platform] of defaults)if(!d.investments.accounts.some(a=>a.platform===platform))d.investments.accounts.push({id:uid(),name,platform,valueEUR:0,positions:[],updatedAt:null});for(const a of d.investments.accounts){a.id??=uid();a.name??='Portefeuille';a.platform??='other';a.valueEUR=Number(a.valueEUR||0);a.positions=Array.isArray(a.positions)?a.positions:[];a.updatedAt??=null}for(const s of Object.values(d.spaces)){if(!Array.isArray(s.incomeSources))s.incomeSources=[incomeSource('Revenu',Number(s.income||0))];s.envelopes=Array.isArray(s.envelopes)?s.envelopes:[];for(const e of s.envelopes){e.id??=uid();e.name??='Poste';e.description??='';e.icon??='•';e.expenses=Array.isArray(e.expenses)?e.expenses:[];e.type=['expense','savings','transfer'].includes(e.type)?e.type:'expense';for(const x of e.expenses){x.id??=uid();x.amount=Number(x.amount||0)}}}d.version=VERSION;return d}
async function load(){const loaded=await BudgetStorage.load();state=normalize(loaded.state)||seed();if(!['overview','personal','shared','future','investments','settings'].includes(state.activeTab))state.activeTab='overview';if(loaded.source!=='indexeddb')save(false);render()}
function save(snapshot=true){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{state.version=VERSION;state.meta.revision=(state.meta.revision||0)+1;state.meta.lastSavedAt=new Date().toISOString();saveQueue=saveQueue.then(()=>BudgetStorage.save(structuredClone(state),{snapshot}));renderSaveStatus()},180)}
function flushSave(){clearTimeout(saveTimer);return BudgetStorage.save(structuredClone(state),{snapshot:false})}
function renderSaveStatus(){const v=state.meta.lastSavedAt?new Date(state.meta.lastSavedAt).toLocaleString('fr-FR'):'—';$('#lastSavedPreview').textContent=v;$('#lastSavedHome').textContent=state.meta.lastSavedAt?`Enregistré ${new Date(state.meta.lastSavedAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}`:'Sauvegarde automatique active'}
function activeSpace(){return state.spaces[state.activeTab==='shared'?'shared':'personal']}
function render(){const tab=state.activeTab;$$('.view').forEach(v=>v.classList.remove('active'));const target=tab==='overview'?els.overview:tab==='future'?els.future:tab==='investments'?els.investments:tab==='settings'?els.settings:els.space;target.classList.add('active');$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const names={overview:['VUE D’ENSEMBLE','Accueil'],personal:['ESPACE PERSONNEL',state.spaces.personal.name],shared:['ESPACE PARTAGÉ',state.spaces.shared.name],future:['TRÉSORERIE FUTURE','À venir'],investments:['PATRIMOINE','Investissements'],settings:['APPLICATION','Réglages']};[els.eyebrow.textContent,els.title.textContent]=names[tab];els.privacy.textContent=state.settings.privacy?'○':'◉';if(tab==='overview')renderOverview();if(tab==='personal'||tab==='shared')renderSpace();if(tab==='future')renderFuture();if(tab==='investments')renderInvestments();if(tab==='settings')renderSettings();renderSaveStatus()}
function renderOverview(){els.overviewCards.innerHTML='';for(const key of ['personal','shared']){const t=totals(state.spaces[key]),c=document.createElement('article');c.className='card overview-card';c.innerHTML=`<small>${key==='personal'?'Personnel':'Compte commun'}</small><strong>${fmt(t.available)}</strong><div class="mini-grid"><div><small>Rentrées</small><b>${fmt(t.income)}</b></div><div><small>Sorties</small><b>${fmt(t.outgoing)}</b></div></div>`;els.overviewCards.append(c)}const inv=sum(state.investments.accounts.map(a=>a.valueEUR));$('#investmentHomeCard').innerHTML=`<article class="card overview-card" style="margin-top:12px;min-height:135px"><small>Investissements</small><strong>${fmt(inv)}</strong><div class="mini-grid"><div><small>Portefeuilles</small><b>${state.investments.accounts.length}</b></div><div><small>Mis à jour</small><b>${latestInvestmentDate()}</b></div></div></article>`}
function renderSpace(){const t=totals(activeSpace());els.available.textContent=fmt(t.available);els.available.className=t.available<0?'negative':'';els.income.textContent=fmt(t.income);els.outgoing.textContent=fmt(t.outgoing);els.incomeList.replaceChildren();for(const src of activeSpace().incomeSources){const r=document.createElement('div');r.className='income-row';r.innerHTML='<div class="copy"><strong></strong><small>Rentrée d’argent</small></div><b></b><button>•••</button>';r.querySelector('strong').textContent=src.label;r.querySelector('b').textContent=fmt(src.amount);r.querySelector('button').onclick=()=>openIncome(src.id);els.incomeList.append(r)}els.posts.replaceChildren();for(const e of activeSpace().envelopes)els.posts.append(renderPost(e))}
function typeLabel(t){return t==='transfer'?'Transfert':t==='savings'?'Épargne':'Dépense'}
function renderPost(e){const n=els.template.content.firstElementChild.cloneNode(true);n.dataset.id=e.id;n.classList.toggle('open',e.id===openId);n.querySelector('.post-icon').textContent=e.icon;n.querySelector('.post-copy strong').textContent=e.name;n.querySelector('.post-copy small').textContent=`${typeLabel(e.type)} · ${e.description||'Sans description'}`;n.querySelector('.post-amount').textContent=fmt(spent(e));n.querySelector('.post-summary').onclick=()=>{openId=openId===e.id?null:e.id;render()};n.querySelector('.edit-post').onclick=()=>openPost(e.id);n.querySelector('.add-expense').onclick=()=>openExpense(e.id);const list=n.querySelector('.expense-list');if(!e.expenses.length)list.innerHTML='<p class="empty">Aucune ligne enregistrée.</p>';else for(const x of e.expenses){const r=document.createElement('div');r.className='expense-row';r.innerHTML='<strong></strong><span></span><button>•••</button>';r.querySelector('strong').textContent=x.label;r.querySelector('span').textContent=fmt(x.amount);r.querySelector('button').onclick=()=>openExpense(e.id,x.id);list.append(r)}return n}
function renderFuture(){const active=state.forecast.items.filter(i=>i.status!=='done'),payments=sum(active.filter(i=>i.kind==='payment').map(i=>i.amount)),receipts=sum(active.filter(i=>i.kind==='receipt').map(i=>i.amount)),impact=receipts-payments,balance=state.forecast.buffer.current+impact;$('#forecastSummary').innerHTML=`<small>Solde prévisionnel</small><strong class="${balance<0?'negative':''}">${fmt(balance)}</strong><div class="hero-grid"><div><small>Réserve</small><b>${fmt(state.forecast.buffer.current)}</b></div><div><small>Impact futur</small><b class="${impact<0?'negative':'positive'}">${fmt(impact)}</b></div></div>`;renderFutureList('paymentList',active.filter(i=>i.kind==='payment'));renderFutureList('receiptList',active.filter(i=>i.kind==='receipt'));renderFutureList('completedList',state.forecast.items.filter(i=>i.status==='done'))}
function renderFutureList(id,items){const box=$('#'+id);box.innerHTML='';if(!items.length){box.innerHTML='<p class="empty">Aucune opération.</p>';return}for(const i of items){const r=document.createElement('button');r.className='investment-row';r.innerHTML=`<span class="avatar">${i.kind==='receipt'?'＋':'−'}</span><span class="copy"><strong>${esc(i.label)}</strong><small>${i.date?new Date(i.date).toLocaleDateString('fr-FR'):'Sans date'} · ${i.status==='confirmed'?'Confirmé':i.status==='done'?'Terminé':'Prévu'}</small></span><b class="${i.kind==='receipt'?'positive':''}">${fmt(i.amount)}</b>`;r.onclick=()=>openFuture(i.id,i.kind);box.append(r)}}
function latestInvestmentDate(){const dates=state.investments.accounts.map(a=>a.updatedAt).filter(Boolean).sort();return dates.length?new Date(dates.at(-1)).toLocaleDateString('fr-FR'):'—'}
function renderInvestments(){const accounts=state.investments.accounts,total=sum(accounts.map(a=>a.valueEUR));$('#investmentTotal').textContent=fmt(total);$('#accountCount').textContent=accounts.length;$('#investmentUpdated').textContent=latestInvestmentDate();const box=$('#investmentAccounts');box.innerHTML='';for(const a of accounts){const r=document.createElement('article');r.className='card expandable'+(openId===a.id?' open':'');const positions=a.positions.filter(p=>Math.abs(p.quantity)>1e-10);r.innerHTML=`<button class="row"><span class="avatar">${platformIcon(a.platform)}</span><span class="copy"><strong>${esc(a.name)}</strong><small>${positions.length} position${positions.length>1?'s':''} · ${a.updatedAt?new Date(a.updatedAt).toLocaleDateString('fr-FR'):'Jamais importé'}</small></span><b>${fmt(a.valueEUR)}</b></button><div class="details"><div class="detail-actions"><button class="secondary-button edit-account">Modifier</button></div><div class="expense-list">${positions.length?positions.slice(0,40).map(p=>`<div class="expense-row"><strong>${esc(p.asset)}</strong><span>${formatQty(p.quantity)}</span></div>`).join(''):'<p class="empty">Aucune position détectée.</p>'}</div></div>`;r.querySelector('.row').onclick=()=>{openId=openId===a.id?null:a.id;render()};r.querySelector('.edit-account').onclick=()=>openInvestmentAccount(a.id);box.append(r)}const hist=$('#importHistory');hist.innerHTML='';for(const h of state.investments.imports.slice().reverse().slice(0,20)){const r=document.createElement('div');r.className='history-row';r.innerHTML=`<span class="avatar">↑</span><span class="copy"><strong>${esc(h.platformName)}</strong><small>${new Date(h.importedAt).toLocaleString('fr-FR')} · ${h.fileName}</small></span><b>${h.positionsCount}</b>`;hist.append(r)}if(!state.investments.imports.length)hist.innerHTML='<p class="empty">Aucun relevé importé.</p>'}
function platformIcon(p){return p==='trade-republic'?'TR':p==='swissborg'?'SB':p==='meria'?'M':p==='crypto-com'?'C':p==='bourse-direct'?'BD':'↗'}
function formatQty(v){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:8}).format(v)}
function renderSettings(){$('#bufferTargetPreview').textContent=fmt(state.forecast.buffer.target);$('#privacyPreview').textContent=state.settings.privacy?'Activé':'Désactivé'}
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const input=(name,label,value='',type='text',required=true)=>`<div class="form-field"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01" inputmode="decimal"':''} ${required?'required':''}></div>`;
const select=(name,label,opts,val)=>`<div class="form-field"><label>${label}</label><select name="${name}">${opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('')}</select></div>`;
function showEditor(title,eyebrow,fields,ctx,del){editor=ctx;els.dialogTitle.textContent=title;els.dialogEyebrow.textContent=eyebrow;els.fields.innerHTML=fields;els.deleteArea.innerHTML=del?`<button class="delete-button" id="deleteButton" type="button">${del}</button>`:'';if(del)$('#deleteButton').onclick=removeCurrent;els.dialog.showModal()}
function openIncome(id){const x=id?activeSpace().incomeSources.find(v=>v.id===id):null;showEditor(x?'Modifier la rentrée':'Nouvelle rentrée',activeSpace().name.toUpperCase(),input('label','Libellé',x?.label)+input('amount','Montant',x?.amount,'number'),{type:'income',id},x?'Supprimer cette rentrée':null)}
function openPost(id){const e=id?activeSpace().envelopes.find(v=>v.id===id):null;showEditor(e?'Modifier le poste':'Nouveau poste','POSTE FINANCIER',input('name','Nom',e?.name)+input('description','Description',e?.description)+select('type','Nature',['Dépense','Épargne','Transfert'],typeLabel(e?.type||'expense'))+input('icon','Icône',e?.icon||'•'),{type:'post',id},e?'Supprimer ce poste':null)}
function openExpense(postId,id){const e=activeSpace().envelopes.find(v=>v.id===postId),x=id?e.expenses.find(v=>v.id===id):null;showEditor(x?'Modifier la ligne':'Nouvelle ligne',e.name.toUpperCase(),input('label','Libellé',x?.label)+input('amount','Montant',x?.amount,'number'),{type:'expense',postId,id},x?'Supprimer cette ligne':null)}
function openFuture(id,kind){const i=id?state.forecast.items.find(v=>v.id===id):null;showEditor(i?'Modifier l’opération':kind==='receipt'?'Nouvel encaissement':'Nouveau paiement','À VENIR',input('label','Libellé',i?.label)+input('amount','Montant',i?.amount,'number')+input('date','Date',i?.date,'date',false)+select('status','État',['Prévu','Confirmé','Terminé'],i?.status==='confirmed'?'Confirmé':i?.status==='done'?'Terminé':'Prévu'),{type:'future',id,kind},i?'Supprimer cette opération':null)}
function openBuffer(){showEditor('Épargne tampon','RÉSERVE',input('current','Solde actuel',state.forecast.buffer.current,'number')+input('target','Objectif',state.forecast.buffer.target,'number'),{type:'buffer'},null)}
function openInvestmentAccount(id){const a=id?state.investments.accounts.find(x=>x.id===id):null;showEditor(a?'Modifier le portefeuille':'Nouveau portefeuille','INVESTISSEMENTS',input('name','Nom',a?.name)+input('valueEUR','Valeur actuelle en euros',a?.valueEUR,'number'),{type:'investment-account',id},a?'Supprimer ce portefeuille':null)}
els.form.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(els.form));if(editor.type==='income'){let x=editor.id?activeSpace().incomeSources.find(v=>v.id===editor.id):null;if(x)Object.assign(x,{label:d.label,amount:Number(d.amount)});else activeSpace().incomeSources.push(incomeSource(d.label,d.amount))}if(editor.type==='post'){let p=editor.id?activeSpace().envelopes.find(v=>v.id===editor.id):null;const type=d.type==='Épargne'?'savings':d.type==='Transfert'?'transfer':'expense';if(p)Object.assign(p,{name:d.name,description:d.description,icon:d.icon,type});else activeSpace().envelopes.push(post(d.name,d.description,d.icon,[],type))}if(editor.type==='expense'){const p=activeSpace().envelopes.find(v=>v.id===editor.postId),x=editor.id?p.expenses.find(v=>v.id===editor.id):null;if(x)Object.assign(x,{label:d.label,amount:Number(d.amount)});else p.expenses.push(expense(d.label,d.amount))}if(editor.type==='future'){let i=editor.id?state.forecast.items.find(x=>x.id===editor.id):null;const status=d.status==='Confirmé'?'confirmed':d.status==='Terminé'?'done':'planned';if(i)Object.assign(i,{label:d.label,amount:Number(d.amount),date:d.date||'',status});else state.forecast.items.push({id:uid(),kind:editor.kind,label:d.label,amount:Number(d.amount),date:d.date||'',status,source:'current'})}if(editor.type==='buffer'){state.forecast.buffer.current=Number(d.current);state.forecast.buffer.target=Number(d.target)}if(editor.type==='investment-account'){let a=editor.id?state.investments.accounts.find(x=>x.id===editor.id):null;if(a)Object.assign(a,{name:d.name,valueEUR:Number(d.valueEUR),updatedAt:new Date().toISOString()});else state.investments.accounts.push({id:uid(),name:d.name,platform:'other',valueEUR:Number(d.valueEUR),positions:[],updatedAt:new Date().toISOString()})}save();els.dialog.close();render()};
function removeCurrent(){if(!confirm('Confirmer la suppression ?'))return;if(editor.type==='income')activeSpace().incomeSources=activeSpace().incomeSources.filter(x=>x.id!==editor.id);if(editor.type==='post')activeSpace().envelopes=activeSpace().envelopes.filter(x=>x.id!==editor.id);if(editor.type==='expense'){const p=activeSpace().envelopes.find(x=>x.id===editor.postId);p.expenses=p.expenses.filter(x=>x.id!==editor.id)}if(editor.type==='future')state.forecast.items=state.forecast.items.filter(x=>x.id!==editor.id);if(editor.type==='investment-account')state.investments.accounts=state.investments.accounts.filter(x=>x.id!==editor.id);save();els.dialog.close();render()}
function parseCSV(text){const first=text.split(/\r?\n/,1)[0],delimiter=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===delimiter&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function detectRows(rows,fileName){const flat=rows.slice(0,20).flat().join(' | ').toLowerCase();if(flat.includes('blocknodes sas')||flat.includes('gross amount (usd)'))return {platform:'swissborg',name:'SwissBorg'};if(flat.includes('transaction kind')&&flat.includes('native amount'))return {platform:'crypto-com',name:'Crypto.com'};if(flat.includes('operation type')&&flat.includes('product name')&&flat.includes('exchange volume'))return {platform:'meria',name:'MERIA'};if(flat.includes('trade republic')||flat.includes('isin')&&flat.includes('shares'))return {platform:'trade-republic',name:'Trade Republic'};if(flat.includes('bourse direct'))return {platform:'bourse-direct',name:'Bourse Direct'};return {platform:'other',name:fileName.replace(/\.[^.]+$/,'')}}
function num(v){if(typeof v==='number')return v;return Number(String(v??'').replace(/\s/g,'').replace(',','.'))||0}
function addQty(map,asset,qty){asset=String(asset||'').trim().toUpperCase();if(!asset||['EUR','USD','GBP','CHF'].includes(asset))return;map.set(asset,(map.get(asset)||0)+num(qty))}
function parsePositions(rows,platform){const map=new Map();if(platform==='crypto-com'){const h=rows[0].map(x=>String(x).trim());const ix=n=>h.indexOf(n);for(const r of rows.slice(1)){addQty(map,r[ix('Currency')],r[ix('Amount')]);addQty(map,r[ix('To Currency')],r[ix('To Amount')])}}else if(platform==='swissborg'){const hi=rows.findIndex(r=>r.map(String).includes('Local time'));if(hi>=0){const h=rows[hi].map(x=>String(x).trim()),ix=n=>h.indexOf(n);for(const r of rows.slice(hi+1)){const type=String(r[ix('Type')]||'').toLowerCase(),asset=r[ix('Currency')],amount=num(r[ix('Net amount')]);const sign=['sell','withdrawal','fee'].some(x=>type.includes(x))?-1:1;addQty(map,asset,amount*sign)}}}else if(platform==='meria'){const h=rows[0].map(x=>String(x).trim()),ix=n=>h.indexOf(n);for(const r of rows.slice(1)){const type=String(r[ix('Operation type')]||'').toLowerCase(),status=String(r[ix('Status')]||'').toLowerCase();if(!['completed','paid'].includes(status))continue;let sign=0;if(['deposit','reward','interest'].some(x=>type.includes(x)))sign=1;if(['withdraw','transfer_out'].some(x=>type.includes(x)))sign=-1;if(sign)addQty(map,r[ix('Currency')],num(r[ix('Amount')])*sign)}}else{const h=rows[0].map(x=>String(x).trim().toLowerCase());const assetIx=h.findIndex(x=>['symbol','ticker','currency','instrument','product name'].includes(x));const qtyIx=h.findIndex(x=>x.includes('quantity')||x.includes('shares')||x==='amount');if(assetIx>=0&&qtyIx>=0)for(const r of rows.slice(1))addQty(map,r[assetIx],r[qtyIx])}return [...map].filter(([,q])=>Math.abs(q)>1e-10).map(([asset,quantity])=>({asset,quantity}))}
async function readStatement(file){let rows;if(/\.xlsx?$/i.test(file.name)){if(!window.XLSX)throw new Error('Le lecteur Excel n’est pas disponible. Vérifiez la connexion internet lors du premier lancement.');const data=await file.arrayBuffer(),book=XLSX.read(data,{type:'array'}),sheet=book.Sheets[book.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:true,defval:''})}else rows=parseCSV(await file.text());const detected=detectRows(rows,file.name),positions=parsePositions(rows,detected.platform);return {...detected,fileName:file.name,positions,rowCount:Math.max(0,rows.length-1)}}
async function previewStatements(files){try{pendingStatements=[];for(const f of files)pendingStatements.push(await readStatement(f));$('#statementSummary').innerHTML=pendingStatements.map(s=>`<div class="statement-file"><strong>${esc(s.name)}</strong><small>${esc(s.fileName)} · ${s.positions.length} position${s.positions.length>1?'s':''} détectée${s.positions.length>1?'s':''}</small></div>`).join('');$('#statementValuation').value='';$('#statementDialog').showModal()}catch(e){alert(e.message||'Impossible de lire ce relevé.')}}
function confirmStatements(){if(!pendingStatements.length)return;const manual=Number($('#statementValuation').value||0),now=new Date().toISOString();pendingStatements.forEach((s,index)=>{let a=state.investments.accounts.find(x=>x.platform===s.platform);if(!a){a={id:uid(),name:s.name,platform:s.platform,valueEUR:0,positions:[],updatedAt:null};state.investments.accounts.push(a)}a.positions=s.positions;a.updatedAt=now;if(manual&&pendingStatements.length===1)a.valueEUR=manual;state.investments.imports.push({id:uid(),accountId:a.id,platform:s.platform,platformName:a.name,fileName:s.fileName,importedAt:now,positionsCount:s.positions.length,rowCount:s.rowCount})});pendingStatements=[];$('#statementDialog').close();save();render()}
function exportBackup(){const blob=new Blob([JSON.stringify({app:'mon-organisation-financiere',version:VERSION,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`organisation-financiere-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function previewImport(file){try{const raw=JSON.parse(await file.text()),d=normalize(raw);if(!d)throw new Error();pendingImport=d;els.importSummary.innerHTML=`<div class="statement-file"><strong>${d.spaces.personal.envelopes.length+d.spaces.shared.envelopes.length} postes financiers</strong><small>${d.investments.accounts.length} portefeuilles · ${d.investments.imports.length} imports</small></div>`;els.importDialog.showModal()}catch{alert('Cette sauvegarde JSON est invalide ou incompatible.')}}
async function confirmImport(){if(!pendingImport)return;await BudgetStorage.save(structuredClone(state),{snapshot:true});state=pendingImport;pendingImport=null;await BudgetStorage.save(structuredClone(state),{snapshot:true});els.importDialog.close();render();alert('Sauvegarde importée avec succès.')}
async function restore(){const snaps=await BudgetStorage.listSnapshots();if(!snaps.length)return alert('Aucune copie locale disponible.');if(confirm('Restaurer la copie locale la plus récente ?')){state=normalize(snaps[0].state)||state;await BudgetStorage.save(structuredClone(state),{snapshot:false});render()}}
$$('.tab').forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.tab;openId=null;save(false);render()});els.privacy.onclick=()=>{state.settings.privacy=!state.settings.privacy;save(false);render()};$('#addIncomeBtn').onclick=()=>openIncome();$('#addEnvelopeBtn').onclick=()=>openPost();$('#addPaymentBtn').onclick=()=>openFuture(null,'payment');$('#addReceiptBtn').onclick=()=>openFuture(null,'receipt');$('#addInvestmentAccountBtn').onclick=()=>openInvestmentAccount();$('#toggleCompletedBtn').onclick=()=>{$('#completedList').classList.toggle('shown');$('#toggleCompletedBtn').textContent=$('#completedList').classList.contains('shown')?'Masquer les opérations terminées':'Afficher les opérations terminées'};$('#closeDialogBtn').onclick=$('#cancelDialogBtn').onclick=()=>els.dialog.close();$('#statementInput').onchange=e=>{if(e.target.files.length)previewStatements([...e.target.files]);e.target.value=''};$('#closeStatementBtn').onclick=$('#cancelStatementBtn').onclick=()=>{$('#statementDialog').close();pendingStatements=[]};$('#confirmStatementBtn').onclick=confirmStatements;$('#importInput').onchange=e=>{const f=e.target.files[0];if(f)previewImport(f);e.target.value=''};$('#closeImportBtn').onclick=$('#cancelImportBtn').onclick=()=>els.importDialog.close();$('#confirmImportBtn').onclick=confirmImport;$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='export')exportBackup();if(a==='restore')restore();if(a==='privacy'){state.settings.privacy=!state.settings.privacy;save(false);render()}if(a==='buffer')openBuffer();if(a==='reset'&&confirm('Effacer toutes les données locales ?')&&confirm('Cette action est irréversible sans sauvegarde JSON.'))BudgetStorage.clear().then(()=>{state=seed();save();render()})});window.addEventListener('pagehide',flushSave);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushSave()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.warn));load();
